#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/veterinary_db
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#     ddl-auto: update
#
#  ## Hibernate Properties
#  # The SQL dialect makes Hibernate generate better SQL for the chosen database
#    properties:
#      hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect